name: text_game_ui
description: A UI toolkit for writing text-based games.
version: 0.0.0
repository: https://github.com/chrisnorman7/text_game_ui

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  characters: ^1.3.0
  json_annotation: ^4.9.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
